import { Provider } from '@/components/organisms/Providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja_JP">
      <head>
        <style>
          {`
            html, body {
              height: 100%;
              margin: 0;
              padding: 0;
            }
            #__next {
              height: 100%;
            }
          `}
        </style>
      </head>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
